CREATE TABLE [dbo].[Email_QueueArchive] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [EmailAccountId]     SMALLINT       NULL,
    [FromEmail]          VARCHAR (100)  NULL,
    [FromEmailName]      VARCHAR (100)  NULL,
    [ToEmail]            VARCHAR (100)  NULL,
    [ToEmailName]        VARCHAR (100)  NULL,
    [CcEmail]            VARCHAR (100)  NULL,
    [BccEmail]           VARCHAR (100)  NULL,
    [Subject]            NVARCHAR (200) NULL,
    [Body]               NVARCHAR (MAX) NULL,
    [AttachmentFilePath] VARCHAR (250)  NULL,
    [AttachedFileName]   VARCHAR (100)  NULL,
    [FileServerId]       SMALLINT       NULL,
    [SentTries]          SMALLINT       NULL,
    [SentOnDateTimeUtc]  DATETIME       NULL,
    [EmailPriority]      TINYINT        NULL,
    [ThreadLock]         NVARCHAR (100) NULL,
    [DateProcessedUtc]   DATETIME       NULL,
    [Status]             TINYINT        NULL,
    [CreatedDate]        DATETIME       NOT NULL,
    [CreatedByContactId] INT            NOT NULL,
    [UpdatedDate]        DATETIME       NULL,
    [ObjectId]           VARCHAR (40)   NOT NULL,
    CONSTRAINT [PK_Email_QueueArchive] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Email_QueueArchive_Common_FileServer] FOREIGN KEY ([FileServerId]) REFERENCES [dbo].[Common_FileServer] ([Id]),
    CONSTRAINT [FK_Email_QueueArchive_Email_SenderAccount] FOREIGN KEY ([EmailAccountId]) REFERENCES [dbo].[Email_SenderAccount] ([Id])
);

